### ISSUE TITLE
Blog Entry Linux Audio Issue 

### ISSUE THREAD

**Issue by CGPipeliner** [phod/phod.github.io#1]
Hi Philipp, 

I am using an ASUS Zenbook Pro UX550 and installed Fedora 34 on my notebook. I experience the same issue as you had during your Ubuntu installation. Did you find any solution for this?

A friend found a hacky solution to create a new Pro Audio Sound profile where you are able to lower and increase the volume
`#!/bin/bash
pactl set-card-profile alsa_card.pci-0000_00_1f.3 pro-audio`

And then using this script as a startup file. But it would be cool if this hardware issue could be solved as well!

**Comment by phod** [comment]
@CGPipeliner, is this around the volume not adjusting evenly and just toggling between mute and full volume?

I did find a workaround that works well enough for the volume stuff, which I wrote up here: https://askubuntu.com/questions/896835/volume-not-adjusting-ubuntu-16-04/1040832#1040832

**Comment by CGPipeliner** [comment]
@phod great, I found this solution as well and it helped! Thank you very much for the reply!

**Comment by phod** [comment]
No worries, happy to help. :) Have a good day!
